# Generated by Django 4.2.4 on 2023-08-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestOneApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDataModel',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('Occupation', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('MobileNumber', models.CharField(max_length=50)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
