# Generated by Django 4.2.4 on 2023-08-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestOneApp', '0003_alter_sampledatamodel_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledatamodel',
            name='MobileNumber',
            field=models.CharField(max_length=50),
        ),
    ]
